# Structure of the manual {#structure}

This manual should allow users with very limited knowledge in R coding to perform a state-of-the-art analysis of geolocator data. Thus, we start with the very basics of loading packges \@ref(start) and data \@ref(loadingData) and go into more detail along the way. Starting with the initial data editing steps, which we call twilight annotation \@ref(twilight), we provide instructions on how to use several prominent analysis packages, illustrate the general analysis workflow using example data, and provide some recommendations for how to visualize and present your results. We do not cover every available analysis package but focus on what we percieve to be the most freuqently used tools, which are GeoLight \@ref(GeoLight), probGLS \@ref(probGLS), SGAT \@ref(SGAT) and FLightR \@ref(FLightR). Finally, the manual concludes with a recommendation for using Movebank as a data repository for geolocator tracks \@ref(movebank).

## Reproducing the analyses {-}

The manual contains a lot of code that can be copy pasted into your R console (or best into a script) and executed to reproduce the results. In order to do so, you need to have the raw data as well as annotaded twilight files of the datasets we use in this manual (see below). The data needs to be in a specific structure of folders and we do recommend to have similar structure for your own analysis. During the processing of the data we do save intermediate steps that allow to step into the analysis without going through all initial and often time consuming parts. You want to be able to easily find the data and avoid confusion of data between different tags. This becomes especially important if you run analyses for many tags of the same or different species. It is also recommended to create a single R script for each analysis (e.g. for each individual and for e.g. analysis using different tools). We use to name our R scripts using the tag id and the tool e.g. 14SA_SGAT.R.
Since we are dealing with tags from different species, we setup the following structure within the main folder (called _data_):


- RawData
    + LanCol
    + MerApi
    + PasCir
- Results
    + LanCol
    + MerApi
    + PasCir
- RCode
    + LanCol
    + MerApi
    + PasCir

You can download the _Data_ folder with the raw data as well as the annotaded twilight files from www.tba.com. We also recommend to use _R Studio_ and to create a project (File -> NewProject). Save the project file into the existing _Data_ folder. This makes sure that _Data_ is your working directory and it will remain the working directory even if the folder moves around on your drive. Alternatively, you can set the working directory using the \code{setwd()} function. With the suggested folder structure and the raw data and the annotaded twiligth files you should be able to run the code provided in this manual.


## The datasets {-}

To illustrate the capabilities of the different packages, discuss the potential pitfalls and provide some recommendations, we will use raw geolocator data from three individuals of different species.
The data is publised on Movebank \@ref{movebank} and can be downloaded directly using the R package _move_ (to be done and to be tested!).

TagID   |  Species           |   Tag type                            | Movebank information
------  | ---------          | -----------------------------------   | ---------------------
M034    | Red-backed Shrike  | Integio (Migrate Technology Ltd.)     | TBA
xxx     | European bee-eater | PAM (Swiss Ornithological Institute)  | TAB
xxx     | Purple martin      | Custom                                | TBA

Although all of these tag types feature the same general functionality, they differ in some key details. First, tags often differ in the frequency at which they log data. Many tags collect a reading every minute and store the maximal light value every 5 or 10 minutes. Other may store a maximum every 2 minutes. The tag that yielded the Purple martin data set, AVERAGED 1min readings every 10min instead of taking a max. The tag also differ in their sensitivity and how they record light levels. Some tags are sensitive only at low light levels and quick "max out" when they experience a lot of light. As such their light-levels do not have units and are simply an index of light intensity. The Integio tags can record unique light values for all light natural levels on earth, and they store lux values that range from 0 to ~70,000. Depending on the tag type, you may have to perform some preliminary steps like log-transforming your data or time shifting light values for sunsets.